### ISSUE TITLE
no .netstandard2.0 support

### ISSUE THREAD

**Issue by Patrickkk** [Fody/NullGuard#86]
Hi,

It seems there is a bug for .net standard 2.0. im getting an exception when building.
It does work for a .net core console project. but not for a .net standard class librairy

related to #65  
repro: https://github.com/Patrickkk/FodyNullguardNetStandard

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		Fody: An unhandled exception occurred:
    Exception:
    Sequence contains no matching element
    StackTrace:
       at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
       at ReferenceFinder.FindReferences(IAssemblyResolver assemblyResolver, ModuleDefinition moduleDefinition)
       at ModuleWeaver.Execute()
       at lambda_method(Closure , Object )
       at InnerWeaver.ExecuteWeavers() in C:\Code\Fody\Fody\FodyIsolated\InnerWeaver.cs:line 181
       at InnerWeaver.Execute() in C:\Code\Fody\Fody\FodyIsolated\InnerWeaver.cs:line 86
    Source:
    System.Core
    TargetSite:
    TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
    	netStandardTest		1	

Regards,

Patrick

**Comment by SimonCropp** [comment]
the fix is now on nuget. thanks for the repro

**Comment by Patrickkk** [comment]
Works indeed.

**Comment by SimonCropp** [comment]
Sorry for the delay
